### ISSUE TITLE
backoffice > login

### ISSUE THREAD

**Issue by morphine06** [ThatItalianInFrance/canileOffice#20]
- coté client sur la page http://localhost:5173/login lorsque l'on click sur "log in" appeler la route /office/login ; 
    - si le serveur envoie une réponse positive, stocker l'utilisateur et le token et rediriger vers la page "home" ; 
    - sinon afficher un message : le plus simple est de créer un div.alert.alert-danger avec un v-if
- coté serveur, faire la route /office/login
    - chercher l'identifiant et le mot de passe (hasher le mot de passe envoyé du client)
    - envoyer soit une erreur, soit l'utilisateur 
- coté client, dans le router, il va falloir rediriger vers la page de connexion si l'utilisateur n'est pas logué (en fait si l'utilisateur n'est pas stocker dans le localstorage) ; faire un truc qui ressemble à çà : 
```
router.beforeEach((to, from, next) => {
  if (to.matched.some(record => record.meta.requiresAuth)) {
    let u = localStorage.getItem('user')
    const user = u ? JSON.parse(u) : null
    if (user?.token) {
      next()
    } else {
      next({ name: 'login' })
    }
  } else {
    next()
  }
})
```

- coté client, rajouter un bouton "Logout" (par exemple dans la barre tout en haut où il y a le logo), qui va simplement effacer le localstorage et rediriger vers la page de login

...en réalité, une procédure de login est plus compliqué, mais je rajouterais de la complexité dans un second temps... il faudra modifier le code existant.

**Comment by ThatItalianInFrance** [comment]
Log in / ou BO OK
