### ISSUE TITLE
cahier des charges

### ISSUE THREAD

**Issue by morphine06** [ThatItalianInFrance/canileOffice#3]
## Site web

- Homepage : 
    - Actualités défilantes
    - Quelques chiens mis en avant et un lien vers la liste des chiens
-  Liste des chiens
-  Fiche d'un chien
- Formulaire de demande pour venir voir le chien

## Admin

- Accueil 
    - boutons vers les modules
    - statistiques (ce sont des cadres de couleur) :
        - nombre de chiens actuellement pensionnaire
        - stock de nourriture
    - rappels (une liste de choses à faire) :
        - chiens à s'occuper (à vacciner, à faire voir par un vétérinaire, etc...)
- Contacts (contient la liste de tous les utilisateurs : administrateurs, bénévoles, secrétaires, propriétaires, vétérinaires, donateurs...)
    - Visualisation d'une fiche
    - Edition d'une fiche
- Les animaux
    - Liste des animaux
        - Impression d'un pdf sur la fiche animal avec toutes les infos
    - Visualisation d'une fiche
    - Edition d'une fiche : 
        - nom
        - âge ou date de naissance
        - race (table liée)
        - sexe (radio button)
        - date d'entrée au chenil
        - chenil rattaché
        - photos
        - numéro tatouage
        - numéro puce
        - couleur / poil
        - propriétaire (si il est connu ou futur propriétaire)
        - nourriture conseillée (table liée)
        - page d'accueil (permet de mettre cette fiche sur la page d'accueil du site web)
        - événements ; ici cela pourrait être une table qui contient tous les événements sur un animal avec une date : visite d'un vétérinaire, sortie, repas spécial, etc... il s'agit juste de pouvoir saisir une date et un texte (et un fichier peut-être)
        - fichiers attachés
- Calendrier (gestion des bénévoles, sorties programmées, événement sanitaire, etc...)
    - vue calendrier
- Les actualités
    - Liste des actualités
    - Edition d'une fiche
        - titre
        - date début d'affichage
        - date fin d'affichage (optionnel)
        - texte 
- Stock
    - liste des produits
    - édition d'une fiche
        - nom du produit
        - type (table liée)
        - événements (table liée) ; 3 types d'événements : entrée, sortie, inventaire + une quantité
- Les chenils
    - liste des chenils ou centres
    - visualisation d'une fiche avec quelques statistiques
    - édition d'une fiche
        - nom
        - adresse (rue, zip code, ville, pays)

**Comment by ThatItalianInFrance** [comment]
+ poids ou taille dans les details du chien

**Comment by ThatItalianInFrance** [comment]
This is almost complete @morphine06
